#!/usr/bin/env python3
"""Export six human-curated, syllabus-complete hard practice papers.

These are not generated by a marks-only ranking.  Each question was selected
after reading the task for multi-step reasoning, non-routine constraints and
cross-skill demands.  The fixed lists below also make every choice auditable.
"""
from __future__ import annotations

import csv
import json
import re
import shutil
import sqlite3
import tempfile
import zipfile
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from lib import paths  # noqa: E402

DATA = Path(paths.DATA)
ASSETS = DATA  # images and books/ live in data/
DB = Path(paths.DB)
OUT = Path(paths.EXPORTS) / "curated_hard_papers"
IMAGE_REF = re.compile(r"(?<![\w/])((?:img9709|img9231|img9618|img_adm|img_tara)/[^\s\]\)\"']+)")

# Entries are ordered as they appear in the assembled paper.  Every component
# topic has at least one entry; ``reason`` records the qualitative judgement.
PAPERS = (
    {
        "slug": "math_p1_curated_hard_paper", "title": "Mathematics · Pure Mathematics 1",
        "syllabus": "9709", "component": "1", "total": 75,
        "items": (
            ("9709_m21_12_q10", "Circular measure", "Equal-area sector condition becomes a non-routine inequality in a parameter."),
            ("9709_s23_11_q12", "Coordinate geometry", "Links two circles, a tangent and exact surd intersections."),
            ("9709_w24_12_q10", "Differentiation", "Requires integration from a derivative plus discriminant-based monotonicity reasoning."),
            ("9709_m25_12_q11", "Functions", "Combines inverse composition, transformations and a range constraint."),
            ("9709_w22_13_q10", "Integration", "Circle-line intersections feed into an exact volume of revolution and perimeter."),
            ("9709_w24_12_q09", "Quadratics", "A parameterised curve-line system includes a no-intersection inequality case."),
            ("9709_s23_13_q08", "Series", "Switches between geometric and arithmetic interpretations with an inequality on n."),
            ("9709_w24_11_q08", "Trigonometry", "Uses identities and a full-domain equation rather than direct substitution."),
        ),
    },
    {
        "slug": "math_s1_curated_hard_paper", "title": "Mathematics · Probability & Statistics 1",
        "syllabus": "9709", "component": "5", "total": 50,
        "items": (
            ("9709_w25_53_q04", "Discrete random variables", "Defines a non-standard maximum random variable and then mixes in a geometric event."),
            ("9709_m23_52_q07", "Permutations and combinations", "Repeated objects, restrictions and a conditional selection count in one task."),
            ("9709_w21_53_q07", "Probability", "A transfer experiment with an unknown parameter and reverse conditional probability."),
            ("9709_w24_52_q06", "Representation of data", "Requires combining two data sets, not merely reading a graph."),
            ("9709_s23_53_q06", "The normal distribution", "Moves between a percentile-derived parameter, binomial events and expected frequency."),
        ),
    },
    {
        "slug": "furthermath_p1_curated_hard_paper", "title": "Further Mathematics · Further Pure Mathematics 1",
        "syllabus": "9231", "component": "1", "total": 75,
        "items": (
            ("9231_w22_11_q05", "Matrices", "Composes transformations, reverses them and analyses invariant lines parametrically."),
            ("9231_w25_12_q05", "Polar coordinates", "Connects polar geometry, exact area and a derived Cartesian equation."),
            ("9231_w25_12_q03", "Proof by induction", "Induction on a rational recurrence followed by a monotonicity proof."),
            ("9231_s22_11_q05", "Rational functions and graphs", "Asymptotes, stationary points, modulus graph and a four-root condition."),
            ("9231_w23_12_q04", "Roots of polynomial equations", "Transforms roots and requires negative power sums."),
            ("9231_s25_13_q04", "Summation of series", "A high-degree telescoping construction with convergence conditions."),
            ("9231_s23_11_q07", "Vectors", "Intersects planes then constrains a line via distance and an obtuse angle."),
        ),
    },
    {
        "slug": "furthermath_s1_curated_hard_paper", "title": "Further Mathematics · Further Probability & Statistics",
        "syllabus": "9231", "component": "4", "total": 50,
        "items": (
            ("9231_s23_41_q06", "Continuous random variables", "Works through CDF, a transformed variable, percentiles and a non-elementary density."),
            ("9231_s24_43_q06", "Inference using normal and t-distributions", "Two-sample confidence interval and directional hypothesis test with unequal variances."),
            ("9231_w23_41_q06", "Non-parametric tests", "Paired observations require the correct non-parametric test and contextual conclusion."),
            ("9231_w25_42_q06", "Probability generating functions", "Extracts moments from non-trivial PGFs and convolves independent variables."),
            ("9231_s23_41_q03", "χ-tests", "Goodness-of-fit test requires completing expected frequencies and handling test conditions."),
        ),
    },
    {
        "slug": "cs_p1_curated_hard_paper", "title": "Computer Science · Theory Fundamentals",
        "syllabus": "9618", "component": "1", "total": 75,
        "items": (
            ("9618_w22_13_q07", "Communication", "Applies subnetting, satellite trade-offs and cloud/network terminology in one scenario."),
            ("9618_s21_11_q07", "Databases", "Tests data modelling, normalisation constraints and DDL rather than isolated definitions."),
            ("9618_w24_12_q05", "Ethics and Ownership", "Requires justified licensing and copyright decisions in a workplace context."),
            ("9618_w22_13_q10", "Hardware", "Uses feedback, sensors and embedded-system properties in an applied system."),
            ("9618_w24_13_q06", "Information representation", "Covers character sets, bitmap storage and lossy digitisation/compression."),
            ("9618_w23_11_q08", "Processor Fundamentals", "Requires instruction-set reasoning and assembly-level program tracing."),
            ("9618_s22_13_q05", "Security, privacy and data integrity", "Distinguishes security, verification, validation and residual correctness risk."),
            ("9618_w25_12_q10", "System Software", "Contrasts interpreter/compiler use and authentic software distribution."),
        ),
    },
    {
        "slug": "cs_p2_curated_hard_paper", "title": "Computer Science · Problem-solving and Programming Skills",
        "syllabus": "9618", "component": "2", "total": 75,
        "items": (
            ("9618_w22_21_q06", "Algorithm Design and Problem-solving", "Trace-table debugging of a flawed validation algorithm tests precise control flow."),
            ("9618_w22_22_q07", "Algorithm Design and Problem-solving", "A substantial syntax-checker design requires arrays, searching and robust algorithm structure."),
            ("9618_s21_22_q02", "Software Development", "Combines state modelling, data requirements and operational design decisions."),
            ("9618_s22_22_q08", "Programming", "A large password-manager task requires multi-dimensional arrays, validation and modules."),
            ("9618_w25_23_q08", "Data Types and Structures", "A file/record task requires a complete counting module with defensive cases."),
        ),
    },
)


def rewrite_images(text: str, images: dict[str, Path]) -> str:
    def replace(match: re.Match[str]) -> str:
        ref = match.group(1)
        images.setdefault(ref, ASSETS / ref)
        return f"images/{ref}"
    return IMAGE_REF.sub(replace, text)


def export_paper(spec: dict) -> Path:
    ids = [item[0] for item in spec["items"]]
    with sqlite3.connect(DB) as con:
        con.row_factory = sqlite3.Row
        placeholders = ",".join("?" for _ in ids)
        found = {row["id"]: row for row in con.execute(
            f"""SELECT id, syllabus, component, paper, session, year, month, q, marks,
                       topic_name, question_latex, question_text, ms_latex, ms_text, image
                  FROM questions WHERE id IN ({placeholders})""", ids)}
    if set(found) != set(ids):
        raise RuntimeError(f"{spec['slug']}: selected IDs are missing from the database")
    rows = [found[item] for item in ids]
    if any(row["syllabus"] != spec["syllabus"] or row["component"] != spec["component"] for row in rows):
        raise RuntimeError(f"{spec['slug']}: an item is in the wrong component")
    marks = sum(row["marks"] or 0 for row in rows)
    if marks != spec["total"]:
        raise RuntimeError(f"{spec['slug']}: {marks} marks, expected {spec['total']}")

    tmp = Path(tempfile.mkdtemp(prefix=f"{spec['slug']}-"))
    try:
        images: dict[str, Path] = {}
        question_lines = [f"# {spec['title']}", "", f"**Curated hard practice paper · {marks} marks**", "",
                          "All questions are past-paper questions assembled into a new practice paper.", ""]
        answer_lines = [f"# {spec['title']} · Mark scheme", ""]
        manifest = []
        coverage_lines = [f"# {spec['title']} · Curation record", "", "Every component topic is represented once or more.", ""]
        for number, ((qid, coverage, reason), row) in enumerate(zip(spec["items"], rows), 1):
            question = rewrite_images(row["question_latex"] or row["question_text"] or "_Question text unavailable._", images)
            scheme = rewrite_images(row["ms_latex"] or row["ms_text"] or "_Mark scheme unavailable._", images)
            if row["image"]:
                images.setdefault(row["image"], ASSETS / row["image"])
            question_lines += ["---", "", f"## Question {number}", ""]
            if row["image"]:
                question_lines += [f"![Question {number}](images/{row['image']})", ""]
            question_lines += [question.strip(), "", f"**[{row['marks']} marks]**", ""]
            answer_lines += ["---", "", f"## Question {number}", "", scheme.strip(), ""]
            coverage_lines += [f"## Question {number} · {coverage}", "", reason, "",
                              f"Source: `{qid}` · {row['paper']} · {row['session']} · {row['marks']} marks.", ""]
            manifest.append({"number": number, "id": qid, "syllabus": row["syllabus"], "component": row["component"],
                             "paper": row["paper"], "session": row["session"], "year": row["year"], "question": row["q"],
                             "marks": row["marks"], "coverage": coverage, "why_selected": reason, "image": row["image"] or ""})

        (tmp / "question_paper.md").write_text("\n".join(question_lines).rstrip() + "\n", encoding="utf-8")
        (tmp / "markscheme.md").write_text("\n".join(answer_lines).rstrip() + "\n", encoding="utf-8")
        (tmp / "curation.md").write_text("\n".join(coverage_lines).rstrip() + "\n", encoding="utf-8")
        (tmp / "index.json").write_text(json.dumps({"title": spec["title"], "total_marks": marks,
            "selection_method": "Human-curated for multi-step/non-routine reasoning and full component-topic coverage.",
            "questions": manifest}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        with (tmp / "index.csv").open("w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=manifest[0].keys())
            writer.writeheader(); writer.writerows(manifest)
        (tmp / "README.md").write_text(
            f"# {spec['title']}\n\n"
            f"This is a {marks}-mark curated hard practice paper, not a marks-sorted export. "
            "`question_paper.md` and `markscheme.md` are separate; all required images are internal under `images/`. "
            "`curation.md` and the index record syllabus coverage and the reason for every selection.\n",
            encoding="utf-8")
        missing = [str(path) for path in images.values() if not path.is_file()]
        if missing:
            raise FileNotFoundError(f"{spec['slug']}: missing images, e.g. {missing[:3]}")
        output = OUT / f"{spec['slug']}.zip"
        with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
            for name in ("README.md", "question_paper.md", "markscheme.md", "curation.md", "index.json", "index.csv"):
                zf.write(tmp / name, f"{spec['slug']}/{name}")
            for ref, source in sorted(images.items()):
                zf.write(source, f"{spec['slug']}/images/{ref}")
        return output
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for spec in PAPERS:
        output = export_paper(spec)
        print(f"{output.name}: {output.stat().st_size / 1024 / 1024:.2f} MiB")


if __name__ == "__main__":
    main()
